### PR TITLE
load function in dnpImport module accepts list of directories

### PR DESCRIPTION
**Pull request by tkeller12**
- [x ] closes issue #97
- [ x] passes `black .`

- [ x] Now Import List of Paths with load function

### CODE REVIEW

**Comment by thcasey3** [comment]
@tkeller12 I see the 'load' function is renamed to 'load_file'? It doesn't just load files, it loads directories as well. Bruker NMR data, for example. This should break most or all of the unittests...

**Comment by thcasey3** [comment]
@tkeller12 there should probably be a unittest added for this

**Comment by thcasey3** [comment]
also, @tkeller12 @thorstenmaly should we add our own exception message for when spectra of different lengths are imported together and can't or shouldn't be concatenated?

**Comment by thcasey3** [comment]
also, @tkeller12 @thorstenmaly what happens if the individuals don't have identical coords? Currently all values arrays of a 2D dataset share a single 1D coords array. If we have it concatenate the individual coords to a 2D coords array all other functions will need to be adjusted to handle 2D coords arrays and mapping of the coords arrays with their corresponding values arrays.

**Comment by thorstenmaly** [comment]
> @tkeller12 there should probably be a unittest added for this

Yes, there should be unittest for that.

**Comment by thorstenmaly** [comment]
> also, @tkeller12 @thorstenmaly should we add our own exception message for when spectra of different lengths are imported together and can't or shouldn't be concatenated?

Tim will add this functionality

**Comment by thorstenmaly** [comment]
> also, @tkeller12 @thorstenmaly what happens if the individuals don't have identical coords? Currently all values arrays of a 2D dataset share a single 1D coords array. If we have it concatenate the individual coords to a 2D coords array all other functions will need to be adjusted to handle 2D coords arrays and mapping of the coords arrays with their corresponding values arrays.

Users should only concatenate same data. Data is intended to have the same coords

**Comment by thcasey3** [comment]
@tkeller12 @thorstenmaly Ok sounds good!

**Pull request merged**
