### PR TITLE
Feature global config

### PR DESCRIPTION
**Pull request by Bkaribo**
- passes pytest, no tests added, figures tested by yen-chun and they look ok, I have looked at the epr_spectrum test example and it seems to be ok
- formatting ok

- introduces a way to read config files that is exposed in the __init__ and introduces a global config file for dnplab (similar to matplotlib)
- the config files are configparser compliant config files with a simplereader (% is the escape character, only % needs to be escaped)
- the config files are searched in the order of current_folder, home_folder, dnplab/config (should always exist!)
- the current_folder config takes precedence over the home_folder which takes precedence over the dnplab/config file

- added a fancyplot_cfg.cfg config file for fancyplot and changed the fancyplot function so that it is now controlled by the fancyplot_cfg.cfg file
- new fancy plots can be added in this cfg file, the syntax is that xlabel, ylabel and title keys are mandatory. they do set the xlabel, ylabel and title. 
- Any key that starts with __ is used for the pyplot.plot function (note that function call kwargs with the same name overwrite these values)
- any key that starts with ax. is applied to the axes object with the string argument that follows (e.g. ax.set_xlabel = myXlabel calls ax.set_xlabel(myXlabel)) if this fails with a ValueError the line is skipped otherwise an error is raised (e.g. you cannot use ax.set_xlim)
- the same is true for keys that start with fig.

- the general dnplab config defines colors. All of them are now automatically added to the pyplot color cycler
- the list of forwarded pyplot plots is now in the general config

### CODE REVIEW

**Comment by Bkaribo** [comment]
forgot two non mandatory values:

coord_scaling -> allows to scale the coordinates
value_scaling ->allows to scale the values

both default to 1

for the show parameters argument:

entries seperated by ;
each entry consists of 3(4) elements that are interpreted as label,attribute,rounding digits, (possible scaling value for the attribute), each element is seperated by ,

showpar = (MyLabel,frequency,2,0.1); (MyOtherLabel,power,2)

would show a box with MyLabel and MyOtherLabel where the spectrometer frequency is scaled by 0.1 and the the power labeled MyOtherLabel is scaled by 1. Both are rounded to two digits

**Comment by Bkaribo** [comment]
now only one configuration file, needs a special module to load the config file to get rid of circular imports

**Comment by tkeller12** [comment]
Can you rename dnplab_cfg.cfg to dnplab.cfg?

**Comment by Bkaribo** [comment]
@TKeller: done & implemented ax.set_xlabel syntax

**Review by tkeller12 — APPROVED** [review]

**Pull request merged**
