### PR TITLE
Updated normalize function

### PR DESCRIPTION
**Pull request by thorstenmaly**
The original value is now divided by the absolute max value to preserve the sign.

### CODE REVIEW

**Comment by Bkaribo** [comment]
About the
get_slice(data, dim, slice_index)
function:

what is the difference between data.\_\_getitem__((dim,indx)) and data.get_slice(dim,index), besides that get slice seems like an explicit method for \_\_getitem__ on a single slice and with different call signature?

a=data['mydim',1]
is the same as
a=data.get_slice('mydim',1)

and I think this will be confusing

**Comment by thorstenmaly** [comment]
Hi Karl,
realize this pull request was a bit premature. I also added the get_slice function and I didn't realize it was in this branch. I agree this is confusing.

**Review by Bkaribo — APPROVED** [review]
I'm ok with this utility function in core/util, despite my comment

**Comment by thorstenmaly** [comment]
I will stash this for now and update it properly

**Pull request closed without merging**
